[workspace]
resolver = "2"
members = [
  "corenn-kernels",
  "hnswlib-rs",
  "libcorenn",
  "corenn",
  "corenn-py",
  "corenn-node",
]

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
